### ISSUE TITLE
Cannot scroll all the way down in /schedule when my browser fills 50% of the window

### ISSUE THREAD

**Issue by xvoorvaa** [efdevcon/streameth#11]
## Expected Behavior

Should scroll all the way down the page

## Current Behavior

There is a limit to scroll. I am missing a part of the last few cards.

## Possible Solution

Unknown

## Steps to Reproduce

1. Open Firefox (v112)
2. Go to `/schedule` (`watch.ethporto.org/schedule`)
3. Make window small enough to only see 2 cards per row.
4. Scroll all the way down.

## Additional information
<img width="961" alt="Screenshot 2023-04-03 at 16 11 59" src="https://user-images.githubusercontent.com/56308735/229535461-8ea8d404-2537-402f-8f23-99eebaa7d0cd.png">

**Comment by pabloVoorvaart** [comment]
FIxed, thank you
