### ISSUE TITLE
Export record streams as an audio only podcast

### ISSUE THREAD

**Issue by clacladev** [efdevcon/streameth#5]
As a user who wants to listen the recorded streams when it's more convenient for me (while commuting), I would like to have all the events whom have been recorded available as a podcast feed. It could be one Podcast feed for the entire event.

So then I can search/add the podcast url in my favourite podcast app.

In the future, it may be useful to be able to select which events I would like to listen later and have a personal podcast feed generated for me. But it's definitely a nice to have, not a must.

**Comment by wslyvh** [comment]
Hi, thanks for your request. Export to audio has been on our list and something we've experimented with for Devcon.
But it hasn't made the final product yet.

I just created an issue on our new repo so we can continue to track it.
This repo will soon be archived.
