### ISSUE TITLE
I want to watch the recorded streams of an event

### ISSUE THREAD

**Issue by clacladev** [efdevcon/streameth#6]
From live.devcon.org I only able to see the live streams per room, but not the ones that have finished. 
I want to watch the recordings, how can I do that?

**Comment by akshaysrivastav** [comment]
I think most talks are viewable here https://www.youtube.com/c/EthereumFoundation/videos

**Comment by clacladev** [comment]
Thanks I was just expecting to be able to see them from the Livepeer network. Is it possible?

**Comment by wslyvh** [comment]
We do have different archive/recording implementations. Best example is up at watch.ethberlin.ooo
Or check out our `live` development branch
https://github.com/efdevcon/streameth/tree/live/src/services
Open to contributions (you seem to be an active Livepeer contributor :))

For Devcon specific, I'd actually recommend to watch from our own video archive https://archive.devcon.org/ 
to gain access to the entire library of Devcon talks with the ease of filtering, playlists, personalized suggestions, decentralized access on IPFS, Swarm and more.
